### ISSUE TITLE
Breaks with multiple contexts

### ISSUE THREAD

**Issue by dillingham** [90poe/vscode-cy-helper#58] opened 2021-06-05 19:19 UTC
![Screen Shot 2021-06-05 at 3 18 02 PM](https://user-images.githubusercontent.com/29180903/120902960-39b77480-c611-11eb-8582-c18c2ad512ba.png)

if you have one file, 2 contexts.. it breaks

```js
context('group / one', () => {

    it('can do thing', () => {
       
    })

    it('can do other thing', () => {
        
    })

})

context('group / two', () => {

    it('can do thing', () => {
       
    })

    it('can do other thing', () => {
        
    })

})```

**Comment by Shelex** [comment] 2021-06-05 21:20
Hi @dillingham 
Thank you for opening an issue.

Seems to me as a duplicate of https://github.com/90poe/vscode-cy-helper/issues/51, however the fix for that was not released due to publish token issues.

**Comment by Shelex** [comment] 2021-07-27 17:46
Hi @dillingham 
Sorry for delayed response. Due to publishing token expiration and missing option to regenerate new one I have published fix for this issue and plugin itself under my personal account from fork.

 - [Cypress Helper v2](https://marketplace.visualstudio.com/items?itemName=shevtsov.vscode-cy-helper)
 - [Repository](https://github.com/Shelex/vscode-cy-helper)
 - In case you have found this extension via pack, it is also republished - [extension pack](https://marketplace.visualstudio.com/items?itemName=shevtsov.qa-extension-pack)

**Closed as completed** 2021-09-21 15:52 UTC
Labels: bug
